# **DATA PREPROCESSING**

# Final Report


Points to be covered -:


*   What is Data preprocessing 
*   How to get dataset
*   Importing the librabries
*   Import the dataset
*   How to handle missing data
*  Categorical data
*   Splitting the dataset into training and test
*  Feature scaling




## What is Data preprocessing ????

#### Data preprocessing is a data mining technique which is used to transform the raw data in a useful and efficient format.

DATA SET IS TAKEN FROM -https://www.superdatascience.com/pages/machine-learning

**IMPORTING LIBRARIES** 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

* Numpy is used to perform Mathematical operations on dataset.
* Matplotlib is used to include sublibrary as pyplot to help plot       amazing graphs.
* Pandas is intutive to import and manage dataset

## **IMPORTING THE DATASET**

In [ ]:
dataset=pd.read_csv('http://www.sharecsv.com/dl/af33c015f16f67e4b2c78403003b4c93/Data.csv')

Here read_csv method is used to read a comma-separated values (csv) file into DataFrame. Also supports optionally iterating or breaking of the file into chunks

In [ ]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### Independent variables (also referred to as Features) are the input for a process that is being analyzes. Dependent variables are the output of the process.

In [ ]:
dataset.head(2)

Country   Age   Salary Purchased
0  France  44.0  72000.0        No
1   Spain  27.0  48000.0       Yes

The head() function is used to get the first n rows.

This function returns the first n rows for the object based on position. It is useful for quickly testing if your object has the right type of data in it.

## **Matrix of Features**

In [ ]:
X= dataset.iloc[:,: -1].values

iloc returns a Pandas Series when one row is selected, and a Pandas DataFrame when multiple rows are selected, or if any column in full is selected. 

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

**VECTOR OF DEPENDENT VARIABLES**

In [ ]:
Y=dataset.iloc[:,3].values

In [ ]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

 **HOW TO HANDLE MISSING VALUES**

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer=imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

By the fit the imputer calculates the means of columns from some data, and by transform it applies those means to some data (which is just replacing missing values with the means)

**CATEGORICAL DATA**

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])

LabelEncoder can be used to normalize labels. It can also be used to transform non-numerical labels (as long as they are hashable and comparable) to numerical labels.

 fit_transform means to do some calculation and then do transformation (say calculating the means of columns from some data and then replacing the missing values). So for training set, you need to both calculate and do transformation.

In [ ]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

![alt text](https://drive.google.com/uc?id=1KMj5akec7PXqLqMtmG4OyFTpyUwlJTf0)

[Dummy Encoding](https://towardsdatascience.com/one-hot-encoding-multicollinearity-and-the-dummy-variable-trap-b5840be3c41a)

**SPLITTING THE DATASET INTO TRAINING AND TEST DATA**

In [ ]:
from sklearn.model_selection  import  train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)


train_test_split is a function in Sklearn model selection for splitting data arrays into two subsets: for training data and for testing data

In [ ]:
X_train


array([[1, 40.0, 63777.77777777778],
       [0, 37.0, 67000.0],
       [2, 27.0, 48000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [2, 38.0, 61000.0],
       [0, 44.0, 72000.0],
       [0, 35.0, 58000.0]], dtype=object)

In [ ]:
Y_train

array(['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes'], dtype=object)

In [ ]:
X_test

array([[1, 30.0, 54000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [ ]:
Y_test

array(['No', 'No'], dtype=object)

## FEATURE SCALING

![alt text](https://drive.google.com/uc?id=1NK5rUbQpYme78TMySEjGDWZy8RX6AbvZ)

Feature scaling  can be an important preprocessing step for many machine learning algorithms. It basically helps to normalise the data within a particular range.

![alt text](https://drive.google.com/uc?id=19g9QR_ZzyoL2A9DEsbdq9rAwcowk_Ivg)

### **![alt text](https://drive.google.com/uc?id=1b3CEf_nhLLsoM0mfKY47Oybwg-j-TNKM)**

Normalization usually means to scale a variable to have a values between 0 and 1, while standardization transforms data to have a mean of zero and a standard deviation of 1.These terms are often used interchangebly.

In [ ]:
from sklearn.preprocessing import StandardScaler 
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [ ]:
X_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

Observe here values are roughly between -2 and +2...

In [ ]:
X_test

array([[ 0.13483997, -1.45882927, -0.90166297],
       [ 0.13483997,  1.98496442,  2.13981082]])